-- The chance of an own line (E.db.customChance): 0 lets every line count the
-- same, above 0 it is the share of emotes that take an own line.

---Runs fn with math.random(100) returning `roll` and math.random(n) for a
---pool returning 1 (the pool's first line).
local function withRoll(roll, fn)
    local original = math.random
    math.random = function(n)
        if n == 100 then return roll end
        return 1
    end
    local ok, err = pcall(fn)
    math.random = original
    if not ok then error(err, 0) end
end

test("a new character counts every line the same", function()
    NewClient():login()
    eq(Saved().customChance, 0)
end)

test("the old 'only my own lines' setting becomes a chance of 100%", function()
    NewClient({ savedDB = { customOnly = true } }):login()
    eq(Saved().customChance, 100)
    eq(Saved().customOnly, nil)
    NewClient({ savedDB = { customOnly = true, customChance = 30 } }):login()
    eq(Saved().customChance, 30, "a chance already set stays")
    NewClient({ savedDB = { customOnly = false } }):login()
    eq(Saved().customChance, 0)
    eq(Saved().customOnly, nil)
end)

test("a broken chance is repaired to a whole percentage from 0 to 100", function()
    NewClient({ savedDB = { customChance = "half" } }):login()
    eq(Saved().customChance, 0)
    NewClient({ savedDB = { customChance = 37.4 } }):login()
    eq(Saved().customChance, 37)
    NewClient({ savedDB = { customChance = 150 } }):login()
    eq(Saved().customChance, 100)
    NewClient({ savedDB = { customChance = -5 } }):login()
    eq(Saved().customChance, 0)
end)

test("/fpe chance sets the percentage; 0 goes back to even", function()
    local client = NewClient():login()
    client:slash("chance 40")
    eq(Saved().customChance, 40)
    ok(client:printedContains("40% of your emotes now want one of your own lines"))
    client:slash("chance 75%")
    eq(Saved().customChance, 75)
    client:slash("chance 0")
    eq(Saved().customChance, 0)
    ok(client:printedContains("every fitting line has the same chance"))
end)

test("/fpe chance without a number from 0 to 100 changes nothing", function()
    local client = NewClient():login()
    client:slash("chance 30")
    for _, bad in ipairs({ "chance", "chance lots", "chance 101", "chance -5", "chance 2.5" }) do
        client.printed = {}
        client:slash(bad)
        eq(Saved().customChance, 30, bad)
        ok(client:printedContains("Give a number from 0 to 100"), bad)
    end
end)

test("with a chance, a roll at or under it takes an own line, above it a built-in one", function()
    local client = NewClient():login()
    client:slash("add Mine.")
    client:slash("chance 30")
    local E = client.E
    withRoll(30, function()
        eq(E.PickLine(nil), "Mine.")
    end)
    withRoll(31, function()
        eq(E.PickLine(nil), E.Locales.enUS.emotes.any[1])
    end)
end)

test("at 0 the own lines simply join the pool", function()
    local client = NewClient():login()
    client:slash("add Mine.")
    withRoll(1, function()
        eq(client.E.PickLine(nil), "Mine.", "the first line of the joined pool is the own one")
    end)
end)

test("at 100% only own lines are used, never a built-in one", function()
    local client = NewClient():login()
    client:slash("add Mine.")
    client:slash("chance 100")
    withRoll(100, function()
        eq(client.E.PickLine(nil), "Mine.")
    end)
end)

test("an own line wanted but none fits: a built-in line, by default", function()
    local client = NewClient():login()
    eq(Saved().customFallback, true)
    client:slash("add [wolf] Wolf line.")
    client:slash("chance 100")
    withRoll(1, function()
        eq(client.E.PickLine(nil), client.E.Locales.enUS.emotes.any[1])
    end)
end)

test("without the fallback such an emote only says who was fed what", function()
    local client = NewClient():login()
    client:slash("add [wolf] Wolf line.")
    client:slash("chance 100")
    client:slash("fallback off")
    eq(Saved().customFallback, false)
    ok(client:printedContains("the emote only says who was fed what"))
    withRoll(1, function()
        eq(client.E.PickLine(nil), nil)
        client:feed(4536)
        eq(client:lastSent().text, "feeds Fluffy a " .. ItemLink(4536) .. ".")
        client:castSucceeded()
        eq(client:lastSent().text, "feeds Fluffy.", "no food either")
    end)
    client:slash("fallback on")
    eq(Saved().customFallback, true)
    ok(client:printedContains("a built-in line is used"))
end)

test("the fallback only matters when an own line is wanted", function()
    local client = NewClient():login()
    client:slash("add [wolf] Wolf line.")
    client:slash("fallback off")
    withRoll(1, function()
        ok(client.E.PickLine(nil), "even: the built-in lines count as usual")
        client:slash("chance 50")
        eq(client.E.PickLine(nil), nil, "a roll of 1 wants an own line")
    end)
    withRoll(51, function()
        eq(client.E.PickLine(nil), client.E.Locales.enUS.emotes.any[1], "a roll above wants a built-in one")
    end)
end)

test("/fpe fallback without on or off changes nothing", function()
    local client = NewClient():login()
    client:slash("fallback maybe")
    eq(Saved().customFallback, true)
    ok(client:printedContains("Emotes are on. Commands:"))
end)

test("a locale without built-in lines falls back on the own ones", function()
    local client = NewClient():login()
    client.E.Emotes = { food = {}, family = {} }
    client:slash("add Mine.")
    client:slash("chance 50")
    withRoll(99, function()
        eq(client.E.PickLine(nil), "Mine.")
    end)
end)

test("the emote uses the picked line", function()
    local client = NewClient():login()
    client:slash("add Mine.")
    client:slash("chance 100")
    withRoll(1, function()
        client:castSucceeded()
        eq(client:lastSent().text, "feeds Fluffy. Mine.")
    end)
end)

test("the panel's slider shows the setting and saves a whole percentage", function()
    local client = NewClient({ savedDB = { customChance = 25 } }):login()
    local slider
    for _, frame in ipairs(client.frames) do
        if frame.kind == "Slider" then slider = frame end
    end
    eq(slider.template, "OptionsSliderTemplate")
    eq(slider.Low:GetText(), "even")
    eq(slider.High:GetText(), "100%")
    client.optionsPanel.scripts.OnShow(client.optionsPanel)
    eq(slider:GetValue(), 25)
    eq(slider.Text:GetText(), "Chance of an own line: 25%")
    slider:SetValue(34.6)
    eq(Saved().customChance, 35)
    eq(slider.Text:GetText(), "Chance of an own line: 35%")
    slider:SetValue(0)
    eq(Saved().customChance, 0)
    eq(slider.Text:GetText(), "Chance of an own line: even")
end)

test("/fpe selftest reports the chance", function()
    local client = NewClient():login()
    client:slash("selftest")
    ok(client:printedContains("Chance of an own line: even (every line counts the same); none fits: a built-in line."))
    client:slash("chance 20")
    client:slash("fallback off")
    client:slash("selftest")
    ok(client:printedContains("Chance of an own line: 20%; none fits: no line."))
end)
