// Refreshes tests/data/forever-food.lua from Wowhead's Forever item lists:
// consumables/food-and-drinks (cooked food and drinks) and trade-goods/meat
// (raw meat, fish and eggs, which pets eat too). Run by hand:
//
//     node tests/fetch-food.mjs
//
// Each row is { item ID, English name, list, article }. The article column is
// what tests/food-names.test.lua expects E.Format("ARTICLE", name) to give.
// Rows already in the file keep their article, since that column is reviewed
// by hand; a new item gets what the addon's rule says now, and is printed so
// it can be checked and corrected in the file.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import fengari from "fengari";

const { lua, lauxlib, lualib, to_luastring, to_jsstring } = fengari;
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const target = join(root, "tests", "data", "forever-food.lua");
const LISTS = [
    ["food", "https://www.wowhead.com/forever/items/consumables/food-and-drinks"],
    ["meat", "https://www.wowhead.com/forever/items/trade-goods/meat"],
];

// The items of one list page: Wowhead embeds them as WH.Gatherer.addData(3, ...).
async function fetchList(url) {
    const response = await fetch(url, { headers: { "User-Agent": "Mozilla/5.0" } });
    if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
    const match = (await response.text()).match(/WH\.Gatherer\.addData\(3, \d+, (\{.*?\})\);/s);
    if (!match) throw new Error(`${url}: no item data found`);
    return JSON.parse(match[1]);
}

// The articles already in the file, by item ID.
function knownArticles() {
    const known = new Map();
    if (!existsSync(target)) return known;
    for (const m of readFileSync(target, "utf8").matchAll(/\{ (\d+), ".*?", "\w+", "(\w+)" \}/g)) {
        known.set(Number(m[1]), m[2]);
    }
    return known;
}

// enUS's ARTICLE, run in fengari: the rule the addon itself uses.
function articleRule() {
    const L = lauxlib.luaL_newstate();
    lualib.luaL_openlibs(L);
    // Family IDs only key the emote tables; any non-nil value will do.
    const setup = `E = { Locales = {}, Family = setmetatable({}, { __index = function(_, k) return k end }) }
        assert(loadfile(...))("FeedPetEmotes", E)`;
    lauxlib.luaL_loadstring(L, to_luastring(setup));
    lua.lua_pushstring(L, to_luastring(join(root, "Locales", "enUS.lua").replace(/\\/g, "/")));
    if (lua.lua_pcall(L, 1, 0, 0) !== 0) throw new Error(to_jsstring(lua.lua_tostring(L, -1)));
    return (name) => {
        lauxlib.luaL_loadstring(L, to_luastring("return E.Locales.enUS.strings.ARTICLE(...)"));
        lua.lua_pushstring(L, to_luastring(name));
        lua.lua_call(L, 1, 1);
        const article = to_jsstring(lua.lua_tostring(L, -1));
        lua.lua_pop(L, 1);
        return article;
    };
}

const known = knownArticles();
const article = articleRule();
const rows = new Map();
for (const [list, url] of LISTS) {
    for (const [id, item] of Object.entries(await fetchList(url))) {
        const name = item.name_enus;
        if (name && name !== "UNUSED ITEM" && !rows.has(Number(id))) rows.set(Number(id), { name, list });
    }
}
const added = [];
const lines = [...rows.entries()]
    .sort((a, b) => a[0] - b[0])
    .map(([id, { name, list }]) => {
        let a = known.get(id);
        if (!a) {
            a = article(name);
            added.push(`${a} ${name} (${id})`);
        }
        return `    { ${id}, ${JSON.stringify(name)}, "${list}", "${a}" },`;
    });

const today = new Date().toISOString().slice(0, 10);
writeFileSync(
    target,
    `-- Generated by tests/fetch-food.mjs on ${today}; the article column is
-- reviewed by hand. { item ID, English name, Wowhead list, article }:
-- "food" is consumables/food-and-drinks, "meat" trade-goods/meat.
return {
${lines.join("\n")}
}
`,
);
console.log(`${rows.size} items written to ${target}`);
if (added.length > 0) console.log(`New, check their article:\n  ${added.join("\n  ")}`);
